# Generated by Django 3.0.8 on 2020-09-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('site', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=5000)),
                ('realse_Date', models.DateField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
