# Generated by Django 3.0.8 on 2020-11-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201120_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students_enrolled',
            field=models.IntegerField(default=0),
        ),
    ]
