# Generated by Django 3.0.8 on 2020-11-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_course_students_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.AddField(
            model_name='course',
            name='Language',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
