# Generated by Django 3.0.8 on 2021-03-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_course_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='main_course',
        ),
    ]
