# Generated by Django 3.0.8 on 2021-03-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210314_1639'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
    ]
